In [3]:
import pandas as pd

# Load the CSV file into a DataFrame
ball_by_ball_data = pd.read_csv('./ipl-dataset-2008-to-2025/ball_by_ball_data.csv')
ipl_matches_data = pd.read_csv('./ipl-dataset-2008-to-2025/ipl_matches_data.csv')
players_data = pd.read_csv('./ipl-dataset-2008-to-2025/players-data-updated.csv')
teams_data = pd.read_csv('./ipl-dataset-2008-to-2025/teams_data.csv')
# View the first 5 rows
# ball_by_ball_data.head()

In [42]:
ipl_matches_data.head()

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,venue,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,M Chinnaswamy Stadium,1,1,6,field,6,140.0,NaN,46.0,win
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,"Rajiv Gandhi International Stadium, Uppal",1,2,1,field,2,35.0,NaN,15.0,win
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Maharashtra Cricket Association Stadium,4,4,3,field,4,NaN,7.0,36.0,win
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Saurashtra Cricket Association Stadium,6,5,6,field,6,NaN,10.0,57.0,win
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Holkar Cricket Stadium,494,494,4,field,494,NaN,6.0,71.0,win

In [37]:
teams_data.head(15)

    team_id                    team_name
0         1  Royal Challengers Bangalore
1         2          Sunrisers Hyderabad
2         3               Mumbai Indians
3         4       Rising Pune Supergiant
4         5                Gujarat Lions
5         6        Kolkata Knight Riders
6       129          Chennai Super Kings
7       134             Rajasthan Royals
8       252               Delhi Capitals
9       494                 Punjab Kings
10      614         Lucknow Super Giants
11      615               Gujarat Titans
12     1068              Deccan Chargers
13     1414         Kochi Tuskers Kerala
14     1419                Pune Warriors

In [35]:
ball_by_ball_data.head()

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,is_bye,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,6,1,0,0,0,...,False,False,0,0,1,0,0,NaN,False,1
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,1,0,...,False,False,0,0,0,0,0,NaN,False,1
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,2,0,...,False,False,1,0,0,0,0,NaN,False,1
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,3,0,...,False,False,0,0,0,0,0,NaN,False,1
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,4,0,...,False,False,0,0,0,0,0,NaN,False,1

In [ ]:
ball_by_ball_data.columns.tolist()

['season_id',
 'match_id',
 'batter',
 'bowler',
 'non_striker',
 'team_batting',
 'team_bowling',
 'over_number',
 'ball_number',
 'batter_runs',
 'extras',
 'total_runs',
 'batsman_type',
 'bowler_type',
 'player_out',
 'fielders_involved',
 'is_wicket',
 'is_wide_ball',
 'is_no_ball',
 'is_leg_bye',
 'is_bye',
 'is_penalty',
 'wide_ball_runs',
 'no_ball_runs',
 'leg_bye_runs',
 'bye_runs',
 'penalty_runs',
 'wicket_kind',
 'is_super_over',
 'innings']

In [31]:
def calculate_batter_performance_metrics(matchup):
    runs = matchup['batter_runs'].sum()
    balls = len(matchup)
    outs = matchup['player_out'].count() # or however your 'out' column is named
    
    sr = (runs / balls) * 100 if balls > 0 else 0
    # Use outs + 1 to avoid division by zero
    impact = sr / ((balls / (outs + 1)) + 1) 
    
    return {"Runs": runs, "Balls": balls, "Outs": outs, "Impact Score": round(impact, 2)}

In [ ]:
def batter_vs_bowler_stats(df, batter, bowler):
    # Use parentheses and & for multiple conditions
    matchup = df[(df['batter'] == batter) & (df['bowler'] == bowler)]
    return calculate_batter_performance_metrics(matchup)

In [34]:
print(batter_vs_bowler_stats(ball_by_ball_data, 'MS Dhoni', 'JJ Bumrah'))

{'Runs': np.int64(62), 'Balls': 68, 'Outs': np.int64(5), 'Impact Score': np.float64(7.39)}

In [38]:
def batter_vs_team_stats(df, batter, team):
    # Use parentheses and & for multiple conditions
    matchup = df[(df['batter'] == batter) & (df['team_bowling'] == team)]
    return calculate_batter_performance_metrics(matchup)

In [41]:
print(batter_vs_team_stats(ball_by_ball_data, 'V Kohli', 3))

{'Runs': np.int64(927), 'Balls': 742, 'Outs': np.int64(29), 'Impact Score': np.float64(4.85)}

In [44]:
def batter_at_venue_stats(df, matches_df, batter, city):
    # Use parentheses and & for multiple conditions
    selected_matches =  matches_df[matches_df['city'] == city]['match_id']
    matchup = df[(df['batter'] == batter) & ball_by_ball_data['match_id'].isin(selected_matches)]
    return calculate_batter_performance_metrics(matchup)

In [49]:
print(batter_at_venue_stats(ball_by_ball_data, ipl_matches_data, 'V Kohli', 'Bangalore'))

{'Runs': np.int64(1874), 'Balls': 1418, 'Outs': np.int64(53), 'Impact Score': np.float64(4.85)}